#!/usr/bin/env ruby

require "sia"
require 'io/console'

def help
  puts <<~HELP
    NAME
        sia -- Encrypting files with digital safes

    SYNOPSIS
        sia command safe_name [filepath]

    DESCRIPTION

        The following commands are available:

        Require a password:

          c[lose]     Save the given file in the given safe
          o[pen]      Open the given file from the given safe
          l[ist]      List information about the given safe
          e[mpty]     Open all files belonging to the given safe
          f[ill]      Close all files belonging to the given safe
          d[elete]    Delete this safe as-is (will not open/close files first)

        No password needed:

          h[elp]      Show this dialog
          v[ersion]   Print the version of this gem

        For more information, visit #{Sia::HOMEPAGE}.

  HELP
end

def doit(name, method, filepath)
  print "Password: "
  password = STDIN.noecho(&:gets).chomp
  puts

  safe = Sia::Safe.new(name: name, password: password)

  case method
  when :close,  :c then safe.close(filepath)
  when :open,   :o then safe.open(filepath)
  when :list,   :l then puts safe.entry.inspect
  when :empty,  :e then safe.empty
  when :fill,   :f then safe.fill
  when :delete, :d then safe.delete
  else
    puts "#{method} is not a recognized argument. See the help info:"
    puts
    help
  end
rescue Sia::PasswordError
  puts "Incorrect Password"
end

case ARGV[0]&.to_sym
when nil, :'--help', :'-h', :h, :help
  help
when :'--version', :'-v', :version, :v
  puts Sia::VERSION
else
  method = ARGV[0].to_sym
  name = ARGV[1]
  filepath = ARGV[2]
  doit(name, method, filepath)
end
